### PR TITLE
2 mock design setup pages

### LINKED ISSUE #2: [Mock Design] Setup pages
Setup pages with
- Own livewire component
- Title for each page
- with web routes

### PR DESCRIPTION
**Pull request by briankarlsayen**
done

### CODE REVIEW

**Comment by briankarlsayen** [comment]
@throwexceptions for code review sir.

**Comment by renitreni** [comment]
@briankarlsayen Remove na lang yung app.blade.php under layouts. baka maging unused code in the future.

Thanks!

**Comment by briankarlsayen** [comment]
@throwexceptions done update for check sir.

**Review by renitreni — APPROVED** [review]
Good to go.

**Pull request merged**
